eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://msvc-student
          predicates:
            - Path=/api/students/**
        - id: courses
          uri: http://msvc-course
          predicates:
            - Path=/api/courses/**
